# Setting up perfSONAR on JS2 + AraHaul

The perfSONAR project maintains a graphical interface to the services directory of all perfSONAR nodes. It can be found at this link: https://stats.perfsonar.net

- ps100g.sdsc.access-ci.org
- ps10g.sdsc.access-ci.org
- ps10g.iu.access-ci.org
- ps100g.iu.access-ci.org
- uct2-net1.mwt2.org
- uct2-net2.mwt2.org
- ps2-hpc-100g.nrel.gov

### perfSONAR Archive on JS2

```
ubuntu@js2-perfsonar-archive:~$ hostname -f
js2-perfsonar-archive.js2local
ubuntu@js2-perfsonar-archive:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8900 qdisc fq_codel state UP group default qlen 1000
    link/ether fa:16:3e:02:76:fe brd ff:ff:ff:ff:ff:ff
    inet 10.0.113.143/24 metric 100 brd 10.0.113.255 scope global dynamic enp1s0
       valid_lft 85886sec preferred_lft 85886sec
    inet6 fe80::f816:3eff:fe02:76fe/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:90:e4:d6:b8 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
ubuntu@js2-perfsonar-archive:~$  curl http://169.254.169.254/latest/meta-data/public-ipv4
149.165.154.129
ubuntu@js2-perfsonar-archive:~$
```

### perfSONAR Testpoint at Wilson Hall on AraHaul

```
root@WilsonHall-Host-000:~# ip addr                                                                                                                                          
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000                                                                                  
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00                                                                                                                    
    inet 127.0.0.1/8 scope host lo                                                                                                                                           
       valid_lft forever preferred_lft forever                                                                                                                               
498: eth0@if499: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1350 qdisc noqueue state UP group default qlen 1000                                                                   
    link/ether fa:16:3e:22:fb:f0 brd ff:ff:ff:ff:ff:ff link-netnsid 0                                                                                                        
    inet 10.0.4.22/24 brd 10.0.4.255 scope global eth0                                                                                                                       
       valid_lft forever preferred_lft forever                                                                                                                               
503: eth1@if11: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default                                                                              
    link/ether 02:42:c0:a8:2a:80 brd ff:ff:ff:ff:ff:ff link-netnsid 0                                                                                                        
    inet 192.168.42.128/24 brd 192.168.42.255 scope global eth1                                                                                                              
       valid_lft forever preferred_lft forever                                                                                                                               
505: eth2@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default                                                                         
    link/ether 68:05:ca:fd:d7:68 brd ff:ff:ff:ff:ff:ff                                                                                                                       
    inet 192.168.0.128/24 brd 192.168.0.255 scope global eth2                                                                                                                
       valid_lft forever preferred_lft forever
```

```
root@WilsonHall-Host-000:/# cat /etc/os-release                                                                                                                              
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"                                                                                                                                 
NAME="Debian GNU/Linux"                                                                                                                                                      
VERSION_ID="11"                                                                                                                                                              
VERSION="11 (bullseye)"                                                                                                                                                      
VERSION_CODENAME=bullseye                                                                                                                                                    
ID=debian                                                                                                                                                                    
HOME_URL="https://www.debian.org/"                                                                                                                                           
SUPPORT_URL="https://www.debian.org/support"                                                                                                                                 
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
2025-09-10 01:12:46,654 INFO exited: pscheduler-ticker (exit status 1; not expected)
2025-09-10 01:12:48,657 INFO spawned: 'pscheduler-ticker' with pid 18471
Traceback (most recent call last):
  File "/usr/lib/pscheduler/daemons/ticker", line 155, in <module>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    main_program()
  File "/usr/lib/pscheduler/daemons/ticker", line 115, in main_program
    db = pscheduler.pg_connection(dsn)
  File "/usr/lib/python3/dist-packages/pscheduler/db.py", line 43, in pg_connection
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    pg = psycopg2.connect(dsn)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/pscheduler/daemons/ticker", line 109, in <lambda>
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

2025-09-10 01:12:48,865 INFO exited: pscheduler-ticker (exit status 1; not expected)
2025-09-10 01:12:51,869 INFO spawned: 'pscheduler-ticker' with pid 18476
Traceback (most recent call last):
  File "/usr/lib/pscheduler/daemons/ticker", line 155, in <module>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    main_program()
  File "/usr/lib/pscheduler/daemons/ticker", line 115, in main_program
    db = pscheduler.pg_connection(dsn)
  File "/usr/lib/python3/dist-packages/pscheduler/db.py", line 43, in pg_connection
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    pg = psycopg2.connect(dsn)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
    self._target(*self._args, **self._kwargs)
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  File "/usr/lib/pscheduler/daemons/ticker", line 109, in <lambda>
psycopg2.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

2025-09-10 01:12:52,076 INFO exited: pscheduler-ticker (exit status 1; not expected)
2025-09-10 01:12:53,077 INFO gave up: pscheduler-ticker entered FATAL state, too many start retries too quickly
```

```
sed -i 's|14|13|g' /etc/supervisord.conf
```

```
2025-09-10 01:21:12,337 INFO stopped: perfsonar-lsregistrationdaemon (terminated by SIGTERM)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Traceback (most recent call last):
  File "/usr/lib/pscheduler/daemons/ticker", line 155, in <module>
    self.run()
  File "/usr/lib/pscheduler/daemons/ticker", line 115, in main_program
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/pscheduler/daemons/ticker", line 109, in <lambda>
    db = pscheduler.pg_connection(dsn)
  File "/usr/lib/python3/dist-packages/pscheduler/db.py", line 43, in pg_connection
    target=lambda: http_queue_maintainer(log))
  File "/usr/lib/pscheduler/daemons/ticker", line 58, in http_queue_maintainer
    pg = psycopg2.connect(dsn)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = pscheduler.pg_connection(dsn)
  File "/usr/lib/python3/dist-packages/pscheduler/db.py", line 43, in pg_connection
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "pscheduler"
```

```
root@WilsonHall-Host-000:~# sed -i '25 s/^/#/' /etc/supervisord.conf
root@WilsonHall-Host-000:~# vi /etc/supervisord.conf
root@WilsonHall-Host-000:~# sed -i '26 s/^/#/' /etc/supervisord.conf
root@WilsonHall-Host-000:~# sed -i '27 s/^/#/' /etc/supervisord.conf
root@WilsonHall-Host-000:~#
```

```
root@WilsonHall-Host-000:~# grep -H ',perfsonar-lsregistrationdaemon' /etc/supervisord.conf 
/etc/supervisord.conf:programs=psconfig-pscheduler-agent,perfsonar-host-exporter,perfsonar-lsregistrationdaemon
root@WilsonHall-Host-000:~# sed -i 's|,perfsonar-lsregistrationdaemon||g' /etc/supervisord.conf 
root@WilsonHall-Host-000:~# grep -H ',perfsonar-lsregistrationdaemon' /etc/supervisord.conf 
root@WilsonHall-Host-000:~# echo $?
1
root@WilsonHall-Host-000:~#
```

```
2025-09-10 01:28:05,434 INFO gave up: pscheduler-scheduler entered FATAL state, too many start retries too quickly
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Traceback (most recent call last):
  File "/usr/lib/pscheduler/daemons/ticker", line 155, in <module>
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    main_program()
  File "/usr/lib/pscheduler/daemons/ticker", line 115, in main_program
    db = pscheduler.pg_connection(dsn)
  File "/usr/lib/python3/dist-packages/pscheduler/db.py", line 43, in pg_connection
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/pscheduler/daemons/ticker", line 109, in <lambda>
    pg = psycopg2.connect(dsn)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
    target=lambda: http_queue_maintainer(log))
  File "/usr/lib/pscheduler/daemons/ticker", line 58, in http_queue_maintainer
    conn = pscheduler.pg_connection(dsn)
  File "/usr/lib/python3/dist-packages/pscheduler/db.py", line 43, in pg_connection
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "pscheduler"

2025-09-10 01:28:05,566 INFO exited: pscheduler-ticker (exit status 1; not expected)
2025-09-10 01:28:06,068 INFO gave up: pscheduler-ticker entered FATAL state, too many start retries too quickly
2025-09-10 01:28:06,069 INFO spawned: 'pscheduler-runner' with pid 19249
Traceback (most recent call last):
  File "/usr/lib/pscheduler/daemons/runner", line 967, in <module>
    main_program()
  File "/usr/lib/pscheduler/daemons/runner", line 791, in main_program
    db = pscheduler.PgConnection(dsn, name="runner")
  File "/usr/lib/python3/dist-packages/pscheduler/db.py", line 95, in __init__
    self.pg = pg_connection(dsn, autocommit=autocommit, name=name)
  File "/usr/lib/python3/dist-packages/pscheduler/db.py", line 43, in pg_connection
    pg = psycopg2.connect(dsn)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "pscheduler"

2025-09-10 01:28:06,571 INFO exited: pscheduler-runner (exit status 1; not expected)
2025-09-10 01:28:07,074 INFO gave up: pscheduler-runner entered FATAL state, too many start retries too quickly
```

### perfSONAR TestPoint at Agronomy Farm on AraHaul

```
root@AgronomyFarm-Host-000:~# ip addr                                                                                                                                        
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000                                                                                  
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00                                                                                                                    
    inet 127.0.0.1/8 scope host lo                                                                                                                                           
       valid_lft forever preferred_lft forever                                                                                                                               
19: eth0@if20: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1350 qdisc noqueue state UP group default qlen 1000                                                                     
    link/ether fa:16:3e:63:61:f0 brd ff:ff:ff:ff:ff:ff link-netnsid 0                                                                                                        
    inet 10.0.4.246/24 brd 10.0.4.255 scope global eth0                                                                                                                      
       valid_lft forever preferred_lft forever                                                                                                                               
24: eth1@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default                                                                          
    link/ether 68:05:ca:fd:f6:1e brd ff:ff:ff:ff:ff:ff                                                                                                                       
    inet 192.168.0.2/24 brd 192.168.0.255 scope global eth1                                                                                                                  
       valid_lft forever preferred_lft forever                                                                                                                               
```

```
2025-09-10 01:12:26,282 INFO exited: pscheduler-runner (exit status 1; not expected)
2025-09-10 01:12:29,286 INFO spawned: 'pscheduler-runner' with pid 18413
Traceback (most recent call last):
  File "/usr/lib/pscheduler/daemons/runner", line 967, in <module>
    main_program()
  File "/usr/lib/pscheduler/daemons/runner", line 791, in main_program
    db = pscheduler.PgConnection(dsn, name="runner")
  File "/usr/lib/python3/dist-packages/pscheduler/db.py", line 95, in __init__
    self.pg = pg_connection(dsn, autocommit=autocommit, name=name)
  File "/usr/lib/python3/dist-packages/pscheduler/db.py", line 43, in pg_connection
    pg = psycopg2.connect(dsn)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

2025-09-10 01:12:29,494 INFO exited: pscheduler-runner (exit status 1; not expected)
2025-09-10 01:12:30,495 INFO gave up: pscheduler-runner entered FATAL state, too many start retries too quickly
```

```
sed -i 's|14|13|g' /etc/supervisord.conf
```

```
root@AgronomyFarm-Host-000:~# pscheduler internal db-update --help
Loading database:
    Administrative...Unable to determine PostgreSQL user.  Is PostgreSQL running?
root@AgronomyFarm-Host-000:~# cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
systemd-network:x:101:102:systemd Network Management,,,:/run/systemd:/usr/sbin/nologin
systemd-resolve:x:102:103:systemd Resolver,,,:/run/systemd:/usr/sbin/nologin
messagebus:x:103:104::/nonexistent:/usr/sbin/nologin
systemd-timesync:x:104:105:systemd Time Synchronization,,,:/run/systemd:/usr/sbin/nologin
sshd:x:105:65534::/run/sshd:/usr/sbin/nologin
perfsonar:x:106:108:perfsonar user,,,:/usr/lib/perfsonar:/usr/sbin/nologin
owamp:x:107:109::/var/lib/owamp:/usr/sbin/nologin
postgres:x:108:111:PostgreSQL administrator,,,:/var/lib/postgresql:/bin/bash
Debian-exim:x:109:112::/var/spool/exim4:/usr/sbin/nologin
twamp:x:110:113::/var/lib/twamp:/usr/sbin/nologin
pscheduler:x:111:114:pscheduler user,,,:/usr/lib/pscheduler:/bin/sh
prometheus:x:999:999:Prometheus services:/usr/share/prometheus:/sbin/nologin
icicle:x:1000:1000::/home/icicle:/bin/bash
root@AgronomyFarm-Host-000:~#
```

### Starting over ...

```
root@WilsonHall-Host-000:~# runuser -u ${PG_USER} -- ${PG_BINDIR}/pg_ctl init -D ${PGDATA}
could not change directory to "/root": Permission denied
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

initdb: error: invalid locale settings; check LANG and LC_* environment variables
pg_ctl: database system initialization failed
root@WilsonHall-Host-000:~#
```

```
root@WilsonHall-Host-000:~# which runuser
/sbin/runuser
root@WilsonHall-Host-000:~# runuser -u ${PG_USER} -- whoami                               
postgres
root@WilsonHall-Host-000:~#
```

```
root@WilsonHall-Host-000:~# su - $PG_USER -c "$PG_BINDIR/pg_ctl init -D $PGDATA"
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: error: directory "/var/lib/postgresql/13/main" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/var/lib/postgresql/13/main" or run initdb
with an argument other than "/var/lib/postgresql/13/main".
pg_ctl: database system initialization failed
root@WilsonHall-Host-000:~#
```

```
root@WilsonHall-Host-000:~# rm -rf $PGDATA
root@WilsonHall-Host-000:~# runuser -u ${PG_USER} -- ${PG_BINDIR}/pg_ctl init -D ${PGDATA}
could not change directory to "/root": Permission denied
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

initdb: error: invalid locale settings; check LANG and LC_* environment variables
pg_ctl: database system initialization failed
root@WilsonHall-Host-000:~# ls -lahtr $PGDATA
ls: cannot access '/var/lib/postgresql/13/main': No such file or directory
root@WilsonHall-Host-000:~# su - $PG_USER -c "$PG_BINDIR/pg_ctl init -D $PGDATA"
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /var/lib/postgresql/13/main ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/lib/postgresql/13/bin/pg_ctl -D /var/lib/postgresql/13/main -l logfile start

root@WilsonHall-Host-000:~#
```



```
root@WilsonHall-Host-000:/tmp# runuser -u ${PG_USER} -- ${PG_BINDIR}/pg_ctl init -D ${PGDATA}
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /var/lib/postgresql/13/main ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/lib/postgresql/13/bin/pg_ctl -D /var/lib/postgresql/13/main -l logfile start

root@WilsonHall-Host-000:/tmp#
```
